### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by romnatson3** [gerdemb/shashin#1]
./shashin.py serve
Loading json features
Traceback (most recent call last):
  File "./shashin.py", line 82, in <module>
    main(sys.argv[1:])
  File "./shashin.py", line 77, in main
    config.cls(config).execute()
  File "/opt/shashin/commands/serve.py", line 70, in execute
    predictor = build_predictor(db, self.cache_dir)
  File "/opt/shashin/predictor.py", line 23, in build_predictor
    print(f"...{len(deleted)} features")
TypeError: object of type 'NoneType' has no len()

**Comment by gerdemb** [comment]
Thank you for the report. This is a hobby project for me, and I will investigate issues when I have time. Any pull requests to fix issues are greatly appreciated.

Just looking at the trace, I think you can just comment out that print statement.

**Comment by gerdemb** [comment]
Fixed in https://github.com/gerdemb/shashin/commit/22aff9bd61edf833d84ba633ea7d4fa1ffb240aa
